### ISSUE TITLE
有没有考虑添加类似one-api类似的GUI呢？

### ISSUE THREAD

**Issue by snakeying** [yym68686/uni-api#1]
虽然one-api很不错，就是带了太多商业化的功能，比如计费之类的。我一直在尝试寻找仅仅是同一接口的应用，这个真的很棒。

通过配置api.yaml非常简单，但对于新手可能有困难，不知道能否提供GUI，那样我觉得适用性更广。

再次感谢

**Comment by yym68686** [comment]
可以，在学习 vue3 中。哈哈，等我学会就加一下😂。

对于程序员来说配置文件更直观。目前我更喜欢配置文件的方式。等有一天配置文件复杂到不直观的时候就是要加前端了。或者某些场景下明显前端更直观优雅，那也一定会安排前端的。

如果你有这样的使用场景，恰好也是我的使用场景，我就积极开发一下前端。

**Comment by snakeying** [comment]
理解，我觉得cli更直观，不过对于大多数普通用户可能就有些technical了。。。只是建议哈，stared~~持续关注中。

PS：如果只是单机使用的情况下问题应该不大，但是如果是部署在公开服务器上，Configuration是不是要考虑加入认证或者密码功能，不然别人改改Configuration再部署一下就完事了。

**Comment by yym68686** [comment]
谢谢关注。我准备前端简单一点，导入导出配置，一个个添加配置这样目前就足够了。后面再说吧，这是目前的想法，项目随着用户增多，各种需求来了，一定会成长的。

公开服务器是指谁都能进的服务器吗。那配置文件可能会被所有人读取（或许可以自己新建一个用户，禁止其他人可读可写是否可行？）。不过我很难想到为什么要部署在公开服务器上。你有这样的应用场景可以描述一下，我才能想到合理的解决方案。😂

**Comment by snakeying** [comment]
抱歉抱歉，可能是我描述有误 😂 我的意思是如果做成GUI的话最好有登录管理，不然每个人都可以进去修改

**Comment by yym68686** [comment]
哦哦，那是肯定的。
