### ISSUE TITLE
api 设置 model 的时候，可不可以加个通配符匹配，比如 gpt4*，匹配名称包含 gpt4 的模型

### ISSUE THREAD

**Issue by DemonJun** [yym68686/uni-api#22]
目前只看到配置 provider/* 的配置方式，没有看到这个模糊匹配模型名称的配置方式

**Comment by DemonJun** [comment]
是的，期待第二点的需求实现，多个渠道都提供对应的 gpt4 模型，但是有的渠道提供的模型带时间版本，使用的时候不好设置。
感谢🙏

**Comment by yym68686** [comment]
> 是的，期待第二点的需求实现，多个渠道都提供对应的 gpt4 模型，但是有的渠道提供的模型带时间版本，使用的时候不好设置。 感谢🙏

目前没实现这个功能，你可以通过重命名模型名来实现通过请求 gpt-3.5-turbo 使用 gpt-3.5-turbo 带日期版本。

**Comment by yym68686** [comment]
> 是的，期待第二点的需求实现，多个渠道都提供对应的 gpt4 模型，但是有的渠道提供的模型带时间版本，使用的时候不好设置。 感谢🙏

你好，第二点已经实现。现在可以通过请求模型名为：gpt-4o* 来匹配带时间的版本了。
