### ISSUE TITLE
可以独立加两个model改名和禁用的设置吗

### ISSUE THREAD

**Issue by BenedictKing** [yym68686/uni-api#23]
现在model不用填可以自己去外部api获取很好，但是这样就没法用模型改名功能了，另外外部api可能有几个模型是不好用的，希望能手动设置禁掉它

**Comment by BenedictKing** [comment]
配置文件会同步显示获取到的模型
--------------------------------
这是会自动改api.yaml吗，没看到有改动啊

**Comment by yym68686** [comment]
> ## 配置文件会同步显示获取到的模型
> 这是会自动改api.yaml吗，没看到有改动啊

你用什么平台部署的？

**Comment by BenedictKing** [comment]
就本地python直接运行main.py

**Comment by BenedictKing** [comment]
哦，我看前端可以用了，挺好
