### ISSUE TITLE
embeddings模型调用出错

### ISSUE THREAD

**Issue by Steven52065** [yym68686/uni-api#35]
使用text-embedding-ada-002模型，docker部署，uni-api:0.0.82
配置
```
providers:
  - provider: ai1 # 服务提供商名称, 如 openai、anthropic、gemini、openrouter、deepbricks，随便取名字，必填
    base_url: https://api....i/v1/chat/completions # 后端服务的API地址，必填
    api: sk-VmW... # 提供商的API Key，必填
    model:
      - gpt-4o
      - chatgpt-4o-latest
      - gpt-4o-mini

  - provider: ai2# 服务提供商名称, 如 openai、anthropic、gemini、openrouter、deepbricks，随便取名字，必填
    base_url: https://api....i/v1/chat/completions # 后端服务的API地址，必填
    api: sk-SO7GS... # 提供商的API Key，必填
    model:
      - gpt-4o
      - chatgpt-4o-latest
      - gpt-4o-mini

api_keys:
  - api: sk-DT0...
    model: 
      - gpt-4o
      - chatgpt-4o-latest
      - gpt-4o-mini
      - text-embedding-ada-002
    preferences:
      RATE_LIMIT: 9999999/hour
  - api: sk-99cM....
    model: 
      - gpt-4o-mini
    preferences:
      RATE_LIMIT: 9999999/hour

preferences: # 全局配置
  model_timeout: # 模型超时时间，单位为秒，默认 100 秒，选填
    gpt-4o: 10 # 模型 gpt-4o 的超时时间为 10 秒,gpt-4o 是模型名称，当请求 gpt-4o-2024-08-06 等模型时，超时时间也是 10 秒
    claude-3-5-sonnet: 10 # 模型 claude-3-5-sonnet 的超时时间为 10 秒，当请求 claude-3-5-sonnet-20240620 等模型时，超时时间也是 10 秒
    default: 10 # 模型没有设置超时时间，使用默认的超时时间 10 秒，当请求的不在 model_timeout 里面的模型时，超时时间默认是 10 秒，不设置 default，uni-api 会使用 环境变量 TIMEOUT 设置的默认超时时间，默认超时时间是 100 秒
    o1-mini: 30 # 
    o1-preview: 100 # 
  cooldown_period: 600 # 
```

日志
```
2024-11-07 14:51:15,048 - uni-api - ERROR - Error processing request or performing moral check: 1 validation error for UnifiedRequest
input
  Input should be a valid string [type=string_type, input_value=[[18259, 238, 37656, 8401...7, 95598, 32307, 56907]], input_type=list]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type
INFO:     172.23.0.1:46232 - "POST /v1/embeddings HTTP/1.1" 422 Unprocessable Entity
2024-11-07 14:51:16,068 - uni-api - ERROR - Error processing request or performing moral check: 1 validation error for UnifiedRequest
input
  Input should be a valid string [type=string_type, input_value=[[78244, 34208, 21043, 20...503, 197, 18, 25, 1419]], input_type=list]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type
INFO:     172.23.0.1:46232 - "POST /v1/embeddings HTTP/1.1" 422 Unprocessable Entity
2024-11-07 14:51:16,847 - uni-api - ERROR - Error processing request or performing moral check: 1 validation error for UnifiedRequest
input
  Input should be a valid string [type=string_type, input_value=[[17599, 113, 47453, 121,...95, 26123, 50667, 1811]], input_type=list]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type
INFO:     172.23.0.1:46232 - "POST /v1/embeddings HTTP/1.1" 422 Unprocessable Entity
```

**Comment by yym68686** [comment]
text-embedding-ada-002 模型只能传入文字，不能传入向量。你再检查一下你的输入。

**Comment by Steven52065** [comment]
> text-embedding-ada-002 模型只能传入文字，不能传入向量。你再检查一下你的输入。

我是在(Dify)[https://github.com/langgenius/dify]中调用的，包括之前用(graphrag)[https://github.com/microsoft/graphrag]好像也不行...

**Comment by yym68686** [comment]
我测试是没有问题的。

<img width="1211" alt="image" src="https://github.com/user-attachments/assets/de716927-0cd7-42df-942d-8976585c7960">

**Comment by yym68686** [comment]
> > text-embedding-ada-002 模型只能传入文字，不能传入向量。你再检查一下你的输入。
> 
> 我是在[Dify](https://github.com/langgenius/dify)中调用的，包括之前用[graphrag](https://github.com/microsoft/graphrag)好像也不行...

感谢测试，该 bug 已修复，重新 pull 最新的 docker 镜像即可。❤️

**Comment by Atomesh** [comment]
> > > text-embedding-ada-002 模型只能格式化文字，不能格式化。你再检查一下你的输入。
> > 
> > 
> > 我正在[Dify](https://github.com/langgenius/dify)中调用，包括用[graphrag](https://github.com/microsoft/graphrag)希望之前也不行...
> 
> 感谢测试，该bug已修复，重新拉取最新的docker镜像即可。❤️

我似乎还是会出现相同，问题，只是 状态码 从 422 变成了 200，不知道是不是我的问题
```
2024-11-07 18:54:37,323 - uni-api - ERROR - Error processing request or performing moral check: 1 validation error for UnifiedRequest

input

  Input should be a valid string [type=string_type, input_value=['# MSDL (MindSearch Dock...lm/internlm2_5-7b-chat'], input_type=list]

    For further information visit https://errors.pydantic.dev/2.9/v/string_type

2024-11-07 18:54:37,379 - uni-api - INFO - provider: Github      model: text-embedding-3-small engine: embedding

INFO:     10.200.0.50:34384 - "POST /v1/embeddings HTTP/1.1" 200 OK
```
我直接使用 curl 请求 Github 的对应链接是正常返回的
```bash
curl -X POST https://models.inference.ai.azure.com/embeddings \
-H "Content-Type: application/json" \
-H "Authorization: Bearer xxxxx" \
-d '{
   "model": "text-embedding-3-large",
   "input": ["First text input", "Second text input", "Third text input"]
}'
```
会正常按照索引对内容进行返回，截了一小段
```
    {
      "object": "embedding",
      "index": 2,
      "embedding": [
        -0.0003535024,
```
我也确认我的版本是最新的
```
root@3fabed17cb77:/home# cat VERSION 
0.0.85
```

有点迷茫

**Comment by yym68686** [comment]
> > > > text-embedding-ada-002 模型只能格式化文字，不能格式化。你再检查一下你的输入。
> > > 
> > > 
> > > 我正在[Dify](https://github.com/langgenius/dify)中调用，包括用[graphrag](https://github.com/microsoft/graphrag)希望之前也不行...
> > 
> > 
> > 感谢测试，该bug已修复，重新拉取最新的docker镜像即可。❤️
> 
> 我似乎还是会出现相同，问题，只是 状态码 从 422 变成了 200，不知道是不是我的问题
> 
> ```
> 2024-11-07 18:54:37,323 - uni-api - ERROR - Error processing request or performing moral check: 1 validation error for UnifiedRequest
> 
> input
> 
>   Input should be a valid string [type=string_type, input_value=['# MSDL (MindSearch Dock...lm/internlm2_5-7b-chat'], input_type=list]
> 
>     For further information visit https://errors.pydantic.dev/2.9/v/string_type
> 
> 2024-11-07 18:54:37,379 - uni-api - INFO - provider: Github      model: text-embedding-3-small engine: embedding
> 
> INFO:     10.200.0.50:34384 - "POST /v1/embeddings HTTP/1.1" 200 OK
> ```
> 
> 我直接使用 curl 请求 Github 的对应链接是正常返回的
> 
> ```shell
> curl -X POST https://models.inference.ai.azure.com/embeddings \
> -H "Content-Type: application/json" \
> -H "Authorization: Bearer xxxxx" \
> -d '{
>    "model": "text-embedding-3-large",
>    "input": ["First text input", "Second text input", "Third text input"]
> }'
> ```
> 
> 会正常按照索引对内容进行返回，截了一小段
> 
> ```
>     {
>       "object": "embedding",
>       "index": 2,
>       "embedding": [
>         -0.0003535024,
> ```
> 
> 我也确认我的版本是最新的
> 
> ```
> root@3fabed17cb77:/home# cat VERSION 
> 0.0.85
> ```
> 
> 有点迷茫

看你的日志出现了一个道德检查的报错，现在已经修复了，不知道会不会解决你的问题。你重复 pull 最新的镜像试试。

**Comment by Atomesh** [comment]
> > > > > text-embedding-ada-002 模型只能格式化文字，不能格式化。你再检查一下你的输入。
> > > > 
> > > > 
> > > > 我正在[Dify](https://github.com/langgenius/dify)中调用，包括用[graphrag](https://github.com/microsoft/graphrag)希望之前也不行...
> > > 
> > > 
> > > 感谢测试，该bug已修复，重新拉取最新的docker镜像即可。❤️
> > 
> > 
> > 我似乎还是会出现相同，问题，只是 状态码 从 422 变成了 200，不知道是不是我的问题
> > ```
> > 2024-11-07 18:54:37,323 - uni-api - ERROR - Error processing request or performing moral check: 1 validation error for UnifiedRequest
> > 
> > input
> > 
> >   Input should be a valid string [type=string_type, input_value=['# MSDL (MindSearch Dock...lm/internlm2_5-7b-chat'], input_type=list]
> > 
> >     For further information visit https://errors.pydantic.dev/2.9/v/string_type
> > 
> > 2024-11-07 18:54:37,379 - uni-api - INFO - provider: Github      model: text-embedding-3-small engine: embedding
> > 
> > INFO:     10.200.0.50:34384 - "POST /v1/embeddings HTTP/1.1" 200 OK
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我直接使用 curl 请求 Github 的对应链接是正常返回的
> > ```shell
> > curl -X POST https://models.inference.ai.azure.com/embeddings \
> > -H "Content-Type: application/json" \
> > -H "Authorization: Bearer xxxxx" \
> > -d '{
> >    "model": "text-embedding-3-large",
> >    "input": ["First text input", "Second text input", "Third text input"]
> > }'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 会正常按照索引对内容进行返回，截了一小段
> > ```
> >     {
> >       "object": "embedding",
> >       "index": 2,
> >       "embedding": [
> >         -0.0003535024,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我也确认我的版本是最新的
> > ```
> > root@3fabed17cb77:/home# cat VERSION 
> > 0.0.85
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 有点迷茫
> 
> 看你的日志出现了一个道德检查的报错，现在已经修复了，不知道会不会解决你的问题。你重复 pull 最新的镜像试试。

我重新使用了镜像，已经不会有报错了，非常感谢
