### ISSUE TITLE
无法在zed编辑器中使用

### ISSUE THREAD

**Issue by ArnoChenFx** [yym68686/uni-api#4]
在使用Zed编辑器中的[自定义endpoint](https://zed.dev/docs/assistant/configuration#custom-endpoint)功能的时候发现uni-api转发的openai api无法正常使用，而使用deepbricks转发的openai api却是正常的。能力有限无法发现问题所在，故创建此issue寻求帮助

**Comment by yym68686** [comment]
是官方API吗？

**Comment by ArnoChenFx** [comment]
> 是官方API吗？

是openai的官方api，而且基本可以确定我的uni-api配置是正确的。因为把uni-api填入到nextchat中是可以正常使用的

**Comment by yym68686** [comment]
好的，我排查一下。我去试试zed。

**Comment by ArnoChenFx** [comment]
> 好的，我排查一下。我去试试zed。

感谢，因为zed还没有发布windows正式版，如果您使用的是windows系统，可以下载[zed nightly build](https://github.com/deevus/zed-windows-builds/releases)

**Comment by yym68686** [comment]
<img width="637" alt="image" src="https://github.com/user-attachments/assets/83765681-7e00-4c60-a205-43696f69051f">


你好，我想问一下，zed在哪里配置第三方url？

**Comment by ArnoChenFx** [comment]
> <img alt="image" width="637" src="https://private-user-images.githubusercontent.com/31803242/364920129-83765681-7e00-4c60-a205-43696f69051f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NjUxNDIsIm5iZiI6MTcyNTU2NDg0MiwicGF0aCI6Ii8zMTgwMzI0Mi8zNjQ5MjAxMjktODM3NjU2ODEtN2UwMC00YzYwLWEyMDUtNDM2OTZmNjkwNTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDE5MzQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2YzA3MzgxYzM2YWIwMzZmZGM3YWMyNjU1NWVkYzBjM2Q5OGIyMWE0NTljMDdkNWJmMWMyZTkyYTFkODBjYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.37WrvmVpMH0ZT0taEw5X1phuTRa94CE2si-cK2IOJ68">
> 
> 你好，我想问一下，zed在哪里配置第三方url？

ctrl+, 或者使用ctrl+shift+p搜索open settings

**Comment by ArnoChenFx** [comment]
![图片](https://github.com/user-attachments/assets/c0dcb6fb-c1f0-4dd6-bf74-26564ce9cffe)

**Comment by yym68686** [comment]
你好，是否可以发一下你的配置，我粘贴一下。

**Comment by ArnoChenFx** [comment]
> 你好，是否可以发一下你的配置，我粘贴一下。

`
{
"language_models": {
    "openai": {
      "api_url": "http://localhost:12513/v1",
      "low_speed_timeout_in_seconds": 5,
      "version": "1",
      "available_models": [
        {
          "name": "openai-gpt-4o",
          "max_tokens": 128000,
          "max_output_tokens": 10000
        }
      ]
    }
  }
}
`

**Comment by ArnoChenFx** [comment]
目前发现的情况是：
1. uni-api正确接收到了来自zed的请求，并向LLM服务提供商正确转发了请求。
2. uni-api从LLM服务提供商获取到了正确的结果，并转返回给了zed。
3. uni-api向zed返回的结果没有被zed正确显示到ui上。

**Comment by yym68686** [comment]
你好，请问是否可以提供一个临时的 OpenAI key，之前别人赞助给我的API已经没额度了，我只需要很小的用量。🥺如果可以的话，可以发我邮箱：yym68686@gmail.com

**Comment by ArnoChenFx** [comment]
> 你好，请问是否可以提供一个临时的 OpenAI key，之前别人赞助给我的API已经没额度了，我只需要很小的用量。🥺如果可以的话，可以发我邮箱：[yym68686@gmail.com](mailto:yym68686@gmail.com)

已发送测试用的Deepbricks API,使用方法等同OpenAI API

**Comment by yym68686** [comment]
> 在使用Zed编辑器中的[自定义endpoint](https://zed.dev/docs/assistant/configuration#custom-endpoint)功能的时候发现uni-api转发的openai api无法正常使用，而使用deepbricks转发的openai api却是正常的。能力有限无法发现问题所在，故创建此issue寻求帮助

谢谢，已经收到，不过你不是说Deepbricks是可用的吗？

**Comment by ArnoChenFx** [comment]
> > 在使用Zed编辑器中的[自定义endpoint](https://zed.dev/docs/assistant/configuration#custom-endpoint)功能的时候发现uni-api转发的openai api无法正常使用，而使用deepbricks转发的openai api却是正常的。能力有限无法发现问题所在，故创建此issue寻求帮助
> 
> 谢谢，已经收到，不过你不是说Deepbricks是可用的吗？

Deepbricks API和OpenAI API都是可以用的。套一层uni-api就无法使用了。我已经发了对应的uni-api的配置参数

**Comment by yym68686** [comment]
好的，我明白了，感谢提供API key。

**Comment by yym68686** [comment]
你好，已经定位到问题：OpenAI消息结尾是\n\r 但是zed只识别\n结尾。我想想怎么解决。

**Comment by yym68686** [comment]
你好，该问题已被修复。

**Comment by ArnoChenFx** [comment]
> 你好，该问题已被修复。

非常感谢您的帮助

**Comment by yym68686** [comment]
有啥问题或者需求都可以提 issue。❤️
