### ISSUE TITLE
 Network error in new_generator: Cancelled by cancel scope 7efe8e13ace0

### ISSUE THREAD

**Issue by jiusheng6** [yym68686/uni-api#5]
INFO:     Will watch for changes in these directories: ['/home']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [1] using StatReload
INFO:     Started server process [8]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
2024-09-09 06:30:03,355 - uni-api - INFO - provider: anthropic  model: claude-3-5-sonnet-20240620 engine: claude
INFO:     103.201.131.152:38206 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-09-09 06:30:05,384 - uni-api - ERROR - Network error in new_generator: Cancelled by cancel scope 7efe8e13ace0

我使用的是GoAmzAI，服务器在美国

**Comment by yym68686** [comment]
本地测试正常吗？或许你可以邮箱私发我一个临时的 API key 和 API url，我这边本地便利测试一下。

**Comment by jiusheng6** [comment]
我对部署的api进行了测试。我发现好像就GoAmzAI会出现问题。
这是GoAmzAI发送的请求信息：
INFO:     127.0.0.1:46450 - "POST /v1/chat/completions HTTP/1.1" 200 OK

请求头:
{
    "host": "127.0.0.1:8000",
    "user-agent": "Go-http-client/1.1",
    "content-length": "3404",
    "accept": "text/event-stream",
    "authorization": "Bearer sk-xxxxxx",
    "cache-control": "no-cache",
    "connection": "keep-alive",
    "content-type": "application/json",
    "accept-encoding": "gzip"
}
请求体:
{
    "model": "claude-3-opus-20240229",
    "messages": [
        {
            "role": "system",
            "content": "# Role: 深搜侍 🔎\n## Profile 📝\n- Name: 深搜侍\n- Language: 中文 \n- Description: 一个全面的信息处理和知识获取的智能助手,通过搜索、分析、总结为用户提供最相关可靠的内容。\n\n## Core Skill 🎯\n自主搜索:根据用户的问题自动提取关键词并利用搜索引擎获取信息。\n\n## Key Features 🌟  \n- 查询理解:准确把握用户问题的核心意图。\n- 多源互证:交叉比对多个来源,确保信息准确性。\n- 逻辑清晰:以条理分明的形式呈现信息和观点。 \n- 要点突出:对关键信息进行强调和汇总。\n\n好的,我根据你的建议对 Interaction Process 部分进行了调整和优化,更适应实际使用流程:\n\n## Interaction Process 🔄\n1. 接收用户的问题,对其进行分析,提取关键词和核心意图。\n2. 利用提取的关键词自动发起网络搜索,获取初步结果。\n3. 根据搜索结果的相关性和可靠性,动态调整后续操作:\n   - 如果结果充分且可靠,直接从中提取关键信息,组织成最终答案;\n   - 如果初步结果不足或不够权威,选取其中最相关的1-2个继续精读,提取信息点,并在必要时发起二次搜索;\n   - 如果搜索未返回有效结果,向用户告知当前查询的局限性,并请求提供更多线索或上下文信息,然后发起新一轮查询。\n4. 对提取的信息进行整合,形成逻辑清晰、表达准确的回答。\n5. 以友好的格式输出答案,同时提供参考链接以供用户进一步查证。\n6. 记录本次查询和结果,优化知识库和查询策略,为之后的问答做准备。\n\n## Reminder 📢\n- 每次回答尽量只使用3-5个最相关可靠的信息来源。\n- 对于无法确定的问题,请明确告知这是基于网络信息做出的判断。\n\n## Output Format 📋\n\n明白了,我对回复格式进行了进一步的优化,使其更加简洁明了、层次分明,同时也突出了关键信息。更新后的输出格式如下:\n\n## Output Format 📋\n\n\n🔍 搜索关键词:提取的查询关键词\n\n💡 核心信息:\n1. 核心信息点1\n   📎 来源:信息来源1\n2. 核心信息点2\n   📎 来源:信息来源2\n3. 核心信息点3\n   📎 来源:信息来源3\n\n🎯 综合回答:\n基于以上信息对问题做出总结回答。回答内容采用简明扼要的语言,突出重点,层次清晰。\n\n🔗 参考链接:\n- 来源1链接\n- 来源2链接\n- 来源3链接\n\n## Initialization 🚀\n你好,我是深搜侍,一个基于搜索的智能问答助手。输入你的问题,我会利用搜索引擎快速找到最相关的信息,经过分析整合后给你一个简明扼要的回复。让我们开始吧,你想了解什么?"
        },
        {
            "role": "user",
            "content": "你好，为什么失败"
        }
    ],
    "stream": true,
    "tools": [
        {
            "type": "function",
            "function": {
                "name": "web_search",
                "description": "使用Google Serper API进行联网搜索并返回结果",
                "parameters": {
                    "properties": {
                        "query": {
                            "description": "要搜索的查询内容",
                            "type": "string"
                        }
                    },
                    "required": [
                        "query"
                    ],
                    "type": "object"
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "summarize_webpage",
                "description": "获取指定网页的内容摘要",
                "parameters": {
                    "properties": {
                        "url": {
                            "description": "要总结的网页URL",
                            "type": "string"
                        }
                    },
                    "required": [
                        "url"
                    ],
                    "type": "object"
                }
            }
        }
    ],
    "tool_choice": "auto"
}

程序会报错：
2024-09-09 09:19:55,786 - uni-api - INFO - provider: anthropic  model: claude-3-opus-20240229 engine: claude
INFO:     103.201.131.152:37448 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-09-09 09:19:59,709 - uni-api - ERROR - Network error in new_generator: Cancelled by cancel scope 7efe8d00e290

我使用python重写：
import requests
import json

# 定义URL
url = "http://x.x.x.x:8001/v1/chat/completions"

# 定义请求头
headers = {
    "host": "127.0.0.1:8000",
    "user-agent": "Go-http-client/1.1",
    "content-length": "2880",
    "accept": "text/event-stream",
    "authorization": "Bearer sk-xxxxx",
    "cache-control": "no-cache",
    "connection": "keep-alive",
    "content-type": "application/json",
    "accept-encoding": "gzip"
}

# 定义请求体
body = {
    "model": "claude-3-opus-20240229",
    "messages": [
        {
            "role": "system",
            "content": "# Role: 深搜侍 🔎\n## Profile 📝\n- Name: 深搜侍\n- Language: 中文 \n- Description: 一个全面的信息处理和知识获取的智能助手,通过搜索、分析、总结为用户提供最相关可靠的内容。\n\n## Core Skill 🎯\n自主搜索:根据用户的问题自动提取关键词并利用搜索引擎获取信息。\n\n## Key Features 🌟  \n- 查询理解:准确把握用户问题的核心意图。\n- 多源互证:交叉比对多个来源,确保信息准确性。\n- 逻辑清晰:以条理分明的形式呈现信息和观点。 \n- 要点突出:对关键信息进行强调和汇总。\n\n好的,我根据你的建议对 Interaction Process 部分进行了调整和优化,更适应实际使用流程:\n\n## Interaction Process 🔄\n1. 接收用户的问题,对其进行分析,提取关键词和核心意图。\n2. 利用提取的关键词自动发起网络搜索,获取初步结果。\n3. 根据搜索结果的相关性和可靠性,动态调整后续操作:\n   - 如果结果充分且可靠,直接从中提取关键信息,组织成最终答案;\n   - 如果初步结果不足或不够权威,选取其中最相关的1-2个继续精读,提取信息点,并在必要时发起二次搜索;\n   - 如果搜索未返回有效结果,向用户告知当前查询的局限性,并请求提供更多线索或上下文信息,然后发起新一轮查询。\n4. 对提取的信息进行整合,形成逻辑清晰、表达准确的回答。\n5. 以友好的格式输出答案,同时提供参考链接以供用户进一步查证。\n6. 记录本次查询和结果,优化知识库和查询策略,为之后的问答做准备。\n\n## Reminder 📢\n- 每次回答尽量只使用3-5个最相关可靠的信息来源。\n- 对于无法确定的问题,请明确告知这是基于网络信息做出的判断。\n\n## Output Format 📋\n\n明白了,我对回复格式进行了进一步的优化,使其更加简洁明了、层次分明,同时也突出了关键信息。更新后的输出格式如下:\n\n## Output Format 📋\n\n\n🔍 搜索关键词:提取的查询关键词\n\n💡 核心信息:\n1. 核心信息点1\n   📎 来源:信息来源1\n2. 核心信息点2\n   📎 来源:信息来源2\n3. 核心信息点3\n   📎 来源:信息来源3\n\n🎯 综合回答:\n基于以上信息对问题做出总结回答。回答内容采用简明扼要的语言,突出重点,层次清晰。\n\n🔗 参考链接:\n- 来源1链接\n- 来源2链接\n- 来源3链接\n\n## Initialization 🚀\n你好,我是深搜侍,一个基于搜索的智能问答助手。输入你的问题,我会利用搜索引擎快速找到最相关的信息,经过分析整合后给你一个简明扼要的回复。让我们开始吧,你想了解什么?"
        },
        {
            "role": "user",
            "content": "你好，为什么失败"
        }
    ],
    "stream": True,
    "tools": [
        {
            "type": "function",
            "function": {
                "name": "web_search",
                "description": "使用Google Serper API进行联网搜索并返回结果",
                "parameters": {
                    "properties": {
                        "query": {
                            "description": "要搜索的查询内容",
                            "type": "string"
                        }
                    },
                    "required": [
                        "query"
                    ],
                    "type": "object"
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "summarize_webpage",
                "description": "获取指定网页的内容摘要",
                "parameters": {
                    "properties": {
                        "url": {
                            "description": "要总结的网页URL",
                            "type": "string"
                        }
                    },
                    "required": [
                        "url"
                    ],
                    "type": "object"
                }
            }
        }
    ],
    "tool_choice": "auto"
}

# 发送请求
response = requests.post(url, headers=headers, data=json.dumps(body))

# 打印响应
print("状态码:", response.status_code)
print("响应体:", response.text)

能够得到正确的返回。

**Comment by jiusheng6** [comment]
那么问题是都出在accept: text/event-stream上呢

**Comment by yym68686** [comment]
意思是你在脚本里加上"accept": "text/event-stream",就没问题，不加这个头一定会报这个错？

**Comment by jiusheng6** [comment]
> 意思是你在脚本里加上"accept": "text/event-stream",就没问题，不加这个头一定会报这个错？

打错字了，我不是很清楚为撒

**Comment by yym68686** [comment]
有没有搭好的GoAmzAI网页，你提供一下临时的API key和API URL，我去测试一下哪里有问题，我仅需要很小的额度就行。email：0okm9ijn@duck.com

**Comment by yym68686** [comment]
可以请求本地 localhost 吗？只要能请求本地调试就比较方便。不太想用微信，你可以在这里或者加我 tg：@yym68686
