### ISSUE TITLE
支持对接azure api中转吗？

### ISSUE THREAD

**Issue by SenLief** [yym68686/uni-api#51]
我好像没看到配置文件中有类似的配置？

**Comment by yym68686** [comment]
不支持，因为我没有 Azure 账号。如果你有额度不知道是否方便提供一下 Azure 配置，帮你适配一下。

**Comment by SenLief** [comment]
> 不支持，因为我没有 Azure 账号。如果你有额度不知道是否方便提供一下 Azure 配置，帮你适配一下。

需要哪些azure的配置？

**Comment by yym68686** [comment]
你好，我看了一下 Azure 官方文档。需要你提供 endpoint，deployment-id，api-key。这三个参数。由于是敏感信息，可以通过 yym68686@outlook.com 邮箱发送给我，当我适配完成后，你可以及时删除。以下是示例 REST API:

```bash
curl https://{endpoint}/openai/deployments/{deployment-id}/completions?api-version=2024-10-21 \
  -H "Content-Type: application/json" \
  -H "api-key: {api-key}" \
  -d '{
  "prompt": [
    "tell me a joke about mango"
  ],
  "max_tokens": 32,
  "temperature": 1.0,
  "n": 1
}'
```

**Comment by yym68686** [comment]
你好，我似乎无法请求成功。可能是因为你手动关闭了吗？我确认一下是不是这个原因。

**Comment by yym68686** [comment]
你好，现在已经支持使用 Azure 模型了。

**Comment by SenLief** [comment]
请求404了，base_url: https://your-endpoint.openai.azure.com，这个只需要替换your-endpoint就可以？还是要填全的终结点地址的

**Comment by SenLief** [comment]
不好意思，忘记重新拉镜像了，重新拉取后可以用了。十分感谢适配！
