### ISSUE TITLE
希望可以支持转发embeddings

### ISSUE THREAD

**Issue by ArnoChenFx** [yym68686/uni-api#7]
https://platform.openai.com/docs/api-reference/embeddings/create

**Comment by yym68686** [comment]
可以的，未来支持了将在这里提醒你。❤️

**Comment by 2447380040** [comment]
同样希望，挺好用的

**Comment by yym68686** [comment]
> 同问，什么时候支持转发embeddings？

已经忙不过来了。正在写前端。自己从头写了一个前端框架，不依赖任何其他人的东西（vue，react等），工作量惊人。就是为了保持 uni-api足够轻量化，还要美观。所以 embeddings 暂时先等等。

**Comment by yym68686** [comment]
已支持 /v1/embeddings 端点。
