### ISSUE TITLE
provider 可以不配置 model 列表，直接从官方请求 Models 列表吗？

### ISSUE THREAD

**Issue by DrayChou** [yym68686/uni-api#9]
请问：

provider 可以不配置 model 列表，直接从官方请求 Models 列表吗？

另外，tools 的配置 可以跟随模型吗？visio 是否支持多模态的 tag 有吗？

谢谢

**Comment by yym68686** [comment]
provider 可以不配置 model 列表，直接从官方请求 Models 列表吗？

- 意思是从/v1/models请求拉模型列表吗？应该是可以的。后面支持一下。

tools 的配置 可以跟随模型吗？

- 这是什么意思。uni-api tools统一用的是OpenAI 格式，自动适配不同的模型。

visio 是否支持多模态的 tag 有吗？

- visio是什么，多模态的 tag 又是什么？

**Comment by DrayChou** [comment]
## tools 的配置 可以跟随模型吗？

比如 ollama ，只有特定的模型才支持 tool 调用，参见：https://ollama.com/blog/tool-support
又比如 豆包，也是只有某些模型才支持 function call

## vision 是否支持多模态的 tag 有吗？

就像 tools 这个状态，ollama 里也是只有特定模型可以支持上传图片进行多模态识别。
而且，openai 也是只有 gpt-4 之后才支持图片上传的。
所以，是否要加一个类似于 tools 的  vision ，用来标识那些大模型支持上传图片。
参见：https://ollama.com/blog/vision-models

谢谢

**Comment by yym68686** [comment]
tools 的配置 可以跟随模型吗？

- 你可以使用README的示例配置文件里面写的：使用tools字段强制开关是否使用tools。

vision 是否支持多模态的 tag 有吗？

- 后面我将添加一个image: true这样的配置强制开启或者关闭图片识别。

**Comment by CodeIntegrity** [comment]
关注一下自动请求models列表

**Comment by yym68686** [comment]
> 关注一下自动请求models列表

好的👌。

**Comment by yym68686** [comment]
> 关注一下自动请求models列表

已添加自动请求模型列表的支持，现在写配置文件不需要必须配置 model 了。代码会自动获取上游的模型名称。

**Comment by BenedictKing** [comment]
> > 关注一下自动请求models列表
> 
> 已添加自动请求模型列表的支持，现在写配置文件不需要必须配置 model 了。代码会自动获取上游的模型名称。

好像不能用这个功能，我把model字段删了，启动显示一些data错误，应该是获取models出错了。
然后请求/models直接显示404

`
NFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [69050] using WatchFiles
INFO:     Started server process [69052]
INFO:     Waiting for application startup.
2024-10-13 16:40:39,670 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-10-13 16:40:39,670 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-10-13 16:40:39,670 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("request_stats")
2024-10-13 16:40:39,670 - sqlalchemy.engine.Engine - INFO - PRAGMA main.table_info("request_stats")
2024-10-13 16:40:39,670 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-10-13 16:40:39,670 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-10-13 16:40:39,671 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("channel_stats")
2024-10-13 16:40:39,671 - sqlalchemy.engine.Engine - INFO - PRAGMA main.table_info("channel_stats")
2024-10-13 16:40:39,671 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-10-13 16:40:39,671 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-10-13 16:40:39,672 INFO sqlalchemy.engine.Engine PRAGMA main.table_xinfo("request_stats")
2024-10-13 16:40:39,672 - sqlalchemy.engine.Engine - INFO - PRAGMA main.table_xinfo("request_stats")
2024-10-13 16:40:39,672 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-10-13 16:40:39,672 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-10-13 16:40:39,672 INFO sqlalchemy.engine.Engine PRAGMA main.table_xinfo("channel_stats")
2024-10-13 16:40:39,672 - sqlalchemy.engine.Engine - INFO - PRAGMA main.table_xinfo("channel_stats")
2024-10-13 16:40:39,672 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-10-13 16:40:39,672 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-10-13 16:40:39,672 INFO sqlalchemy.engine.Engine COMMIT
2024-10-13 16:40:39,672 - sqlalchemy.engine.Engine - INFO - COMMIT
error: 'data'
error: 'data'
error: 'data'
error: 'data'
error: 'data'
error: 'data'
error: 'data'
error: string indices must be integers, not 'str'
INFO:     Application startup complete.
INFO:     127.0.0.1:55227 - "GET /models HTTP/1.1" 404 Not Found
`

**Comment by yym68686** [comment]
@BenedictKing 可能你用的api不符合规范。是否可以发一下你使用的api提供商的url和你的一个临时API key 我测试一下。

**Comment by BenedictKing** [comment]
哦，应该是api设置的格式不对，我之前是
```
- api:
    - sk-12345
```

**Comment by yym68686** [comment]
@BenedictKing 建议用vscode这样的ide编写配置文件。如果你写的格式有错误会自动标红。

**Comment by BenedictKing** [comment]
还是不对，你试一下这个配置
```
  - provider: ephone
    base_url: https://api.ephone.chat/v1/chat/completions
    api: "['sk-X5a3vaQS1xcU3IA8jJRYLGF8dE0mKbEoJQmaBD3Ld8tbSP2o', 'sk-X5a3vaQS1xcU3IA8jJRYLGF8dE0mKbEoJQmaBD3Ld8tbSP2o']"
    model: []
    tools: true
    notes:
```

**Comment by yym68686** [comment]
@BenedictKing 好的。我测试一下。

**Comment by yym68686** [comment]
为什么api你是字符串类型的，应该是下面这样吧？

```
  - provider: ephone
    base_url: https://api.ephone.chat/v1/chat/completions
    api:
      - sk-X5a3vaQS1xcU3IA8jJRYLGF8dE0mKbEoJQmaBD3Ld8tbSP2o
      - sk-X5a3vaQS1xcU3IA8jJRYLGF8dE0mKbEoJQmaBD3Ld8tbSP2o
    model: []
    tools: true
    notes:
```

**Comment by BenedictKing** [comment]
新的前端自动给我改的啊

**Comment by yym68686** [comment]
感谢测试，前端现在可能还有点问题，目前建议还是用配置文件的方式写。我会单独测试这个问题的。

**Comment by yym68686** [comment]
哦哦，我知道了，现在前端还不支持多个API key。所以才会这样。

**Comment by yym68686** [comment]
> 新的前端自动给我改的啊，我原来也是你这个格式

目前多个API key建议手动在配置文件里面改，一旦用前端打开这个配置就会把多个API存成一个API key，这里还不完善。

**Comment by yym68686** [comment]
> 新的前端自动给我改的啊，我原来也是你这个格式

总之现在先别用前端，只写了个最基本的壳。仅有最基本的功能。

**Comment by BenedictKing** [comment]
> 为什么api你是字符串类型的，应该是下面这样吧？
> 
> ```
>   - provider: ephone
>     base_url: https://api.ephone.chat/v1/chat/completions
>     api:
>       - sk-X5a3vaQS1xcU3IA8jJRYLGF8dE0mKbEoJQmaBD3Ld8tbSP2o
>       - sk-X5a3vaQS1xcU3IA8jJRYLGF8dE0mKbEoJQmaBD3Ld8tbSP2o
>     tools: true
> ```

那你用这个配置能自动获取models吗

**Comment by yym68686** [comment]
> > 为什么api你是字符串类型的，应该是下面这样吧？
> > ```
> >   - provider: ephone
> >     base_url: https://api.ephone.chat/v1/chat/completions
> >     api:
> >       - sk-X5a3vaQS1xcU3IA8jJRYLGF8dE0mKbEoJQmaBD3Ld8tbSP2o
> >       - sk-X5a3vaQS1xcU3IA8jJRYLGF8dE0mKbEoJQmaBD3Ld8tbSP2o
> >     tools: true
> > ```
> 
> 那你用这个配置能自动获取models吗

可以。

**Comment by BenedictKing** [comment]
奇怪了，那载入的时候应该有读取models的过程吧，代码中没搜到

**Comment by yym68686** [comment]
@BenedictKing 有的。有个初始化模型的函数。

**Comment by BenedictKing** [comment]
找到了，是这里，api如果是多个，传入的时候就是一个数组，拿去请求鉴权就错误了
```response = httpx.get(
            endpoint_models_url,
            headers={"Authorization": f"Bearer {api}"},
        )```

**Comment by yym68686** [comment]
@BenedictKing 感谢指出错误。我确实没考虑到。我优化一下。

**Comment by BenedictKing** [comment]
在请求上面加这些就行
```
if isinstance(api, list):
    api = api[0]
```

**Comment by yym68686** [comment]
@BenedictKing 你可以提交一个pr我合并一下。

**Comment by BenedictKing** [comment]
好像这些api代理请求models并没有根据不同api key的权限返回不同的可用models列表，应该只用第一个key就行了

**Comment by yym68686** [comment]
@BenedictKing 暂时先这样吧。有用户遇到边缘case到时候再说。❤️

**Comment by BenedictKing** [comment]
> @BenedictKing 你可以提交一个pr我合并一下。

提交pr了

**Comment by yym68686** [comment]
@BenedictKing 已合并。

**Comment by yym68686** [comment]
> 请问：
> 
> provider 可以不配置 model 列表，直接从官方请求 Models 列表吗？
> 
> 另外，tools 的配置 可以跟随模型吗？visio 是否支持多模态的 tag 有吗？
> 
> 谢谢

你好，现在已经支持自定义开启或者关闭识图功能。示例配置：

```yaml
  - provider: openai
    base_url: https:/xxx/v1/messages
    api: sk-keys
    image: true
```

**Comment by yym68686** [comment]
> 还是不对，你试一下这个配置
> 
> ```
>   - provider: ephone
>     base_url: https://api.ephone.chat/v1/chat/completions
>     api: "['sk-X5a3vaQS1xcU3IA8jJRYLGF8dE0mKbEoJQmaBD3Ld8tbSP2o', 'sk-X5a3vaQS1xcU3IA8jJRYLGF8dE0mKbEoJQmaBD3Ld8tbSP2o']"
>     model: []
>     tools: true
>     notes:
> ```

@BenedictKing 你好，现在前端修复了这个 bug，可以显示多个 API key 了。❤️
